# Generated by Django 2.2.6 on 2019-10-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191025_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='soluctions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
