# Generated by Django 2.2.7 on 2019-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='null', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
